model = "gpt-5.6-luna"
network_access = true
model_reasoning_effort = "low"
experimental_use_rmcp_client = true
sandbox_mode = "workspace-write"
personality = "friendly"
plan_mode_reasoning_effort = "high"
approvals_reviewer = "auto_review"

[profiles.openrouter]
model_provider = "openrouter"
model = "openai/gpt-oss-120b:free"

[model_providers.openrouter]
name = "openrouter"
base_url="https://openrouter.ai/api/v1"
env_key="OPENROUTER_API_KEY"

[sandbox_workspace_write]
network_access = true
writable_roots = [ "/Users/yuya/.pm2" ]

[features]
unified_exec = true
shell_snapshot = true
steer = true
apps = true
multi_agent = true

[otel]
environment = "dev"
log_user_prompt = true
exporter = { otlp-grpc = { endpoint = "http://localhost:4317" } }
trace_exporter = { otlp-grpc = { endpoint = "http://localhost:4317" } }
metrics_exporter = { otlp-grpc = { endpoint = "http://localhost:4317" } }

[projects."/Users/yuya/tools"]
trust_level = "trusted"

[projects."/Users/yuya/dev/codex-agent"]
trust_level = "trusted"

[projects."/Users/yuya/dev"]
trust_level = "trusted"

[projects."/Users/yuya/.config/zsh"]
trust_level = "trusted"

[projects."/Users/yuya/.config/nvim"]
trust_level = "trusted"

[projects."/Users/yuya"]
trust_level = "trusted"

[projects."/Users/yuya/dev/experimental"]
trust_level = "trusted"

[projects."/Users/yuya/dev/acurl"]
trust_level = "trusted"

[projects."/Users/yuya/dev/doc-vault"]
trust_level = "trusted"

[projects."/Users/yuya/dev/signoz"]
trust_level = "trusted"

[projects."/Users/yuya/dev/singleton-tabs"]
trust_level = "trusted"

[projects."/Users/yuya/dev/kichige-release"]
trust_level = "trusted"

[projects."/Users/yuya/.codex"]
trust_level = "trusted"

[projects."/Users/yuya/dev/clip-guardian"]
trust_level = "trusted"

[projects."/Users/yuya/dev/keyball44-jis-firmware"]
trust_level = "trusted"

[projects."/Users/yuya/dotfiles"]
trust_level = "trusted"

[projects."/Users/yuya/dev/haskell-mooc"]
trust_level = "trusted"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp"
enabled = false

[tui]
status_line = ["model-with-reasoning", "context-remaining", "current-dir", "git-branch", "context-used", "five-hour-limit"]

[tui.model_availability_nux]
"gpt-5.5" = 1

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."build-ios-apps@openai-curated"]
enabled = true
